//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/APEX/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::G6, // Injector 1
	Gpio::G5, // Injector 2
	Gpio::G4, // Injector 3
	Gpio::G3, // Injector 4
	Gpio::G2, // Injector 5
	Gpio::D15, // Injector 6
	Gpio::D14, // Injector 7
	Gpio::D13, // Injector 8
	Gpio::D12, // AUX 1
	Gpio::D11, // AUX 2
	Gpio::D10, // AUX 3
	Gpio::D9, // AUX 4 (TACHO)
	Gpio::D8, // AUX 5
	Gpio::B12, // AUX 6
	Gpio::B11, // AUX 7
	Gpio::B10, // AUX 8
	Gpio::E15, // Ignition 1
	Gpio::E14, // Ignition 2
	Gpio::E13, // Ignition 3
	Gpio::E12, // Ignition 4
	Gpio::E11, // Ignition 5
	Gpio::E10, // Ignition 6
	Gpio::E9, // Ignition 7
	Gpio::E8, // Ignition 8
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "AUX 1",
// "AUX 2",
// "AUX 3",
// "AUX 4 (TACHO)",
// "AUX 5",
// "AUX 6",
// "AUX 7",
// "AUX 8",
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "Ignition 7",
// "Ignition 8",
}
