//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on /home/gmx/fome-fw/firmware/config/boards/APEX/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::B10: return "AUX 8";
		case Gpio::B11: return "AUX 7";
		case Gpio::B12: return "AUX 6";
		case Gpio::C13: return "Spare trigger input 2";
		case Gpio::D10: return "AUX 3";
		case Gpio::D11: return "AUX 2";
		case Gpio::D12: return "AUX 1";
		case Gpio::D13: return "Injector 8";
		case Gpio::D14: return "Injector 7";
		case Gpio::D15: return "Injector 6";
		case Gpio::D8: return "AUX 5";
		case Gpio::D9: return "AUX 4 (TACHO)";
		case Gpio::E0: return "Digital Input 2";
		case Gpio::E1: return "Digital Input 1";
		case Gpio::E10: return "Ignition 6";
		case Gpio::E11: return "Ignition 5";
		case Gpio::E12: return "Ignition 4";
		case Gpio::E13: return "Ignition 3";
		case Gpio::E14: return "Ignition 2";
		case Gpio::E15: return "Ignition 1";
		case Gpio::E2: return "Digital Input 3";
		case Gpio::E3: return "Digital Input 4";
		case Gpio::E4: return "Spare trigger input 1";
		case Gpio::E5: return "Camshaft Sensor";
		case Gpio::E6: return "Crankshaft Sensor";
		case Gpio::E8: return "Ignition 8";
		case Gpio::E9: return "Ignition 7";
		case Gpio::F0: return "Digital Input 5";
		case Gpio::F1: return "Digital Input 6";
		case Gpio::F2: return "Digital Input 7";
		case Gpio::F6: return "Digital Input 8";
		case Gpio::G2: return "Injector 5";
		case Gpio::G3: return "Injector 4";
		case Gpio::G4: return "Injector 3";
		case Gpio::G5: return "Injector 2";
		case Gpio::G6: return "Injector 1";
		default: return nullptr;
	}
	return nullptr;
}
