pins:
  # Low side outputs
  - pin: 1
    id: G6
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 1
    
  - pin: 2
    id: G5
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 2

  - pin: 3
    id: G4
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 3
    
  - pin: 4
    id: G3
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 4
    
  - pin: 5
    id: G2
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 5
    
  - pin: 6
    id: D15
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 6
    
  - pin: 7
    id: D14
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 7
    
  - pin: 8
    id: D13
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 8

    # Low side

  - pin: 9
    id: D12
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 1

  - pin: 10
    id: D11
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 2

  - pin: 11
    id: D10
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 3

  - pin: 12
    id: D9
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 4 (TACHO)

  - pin: 13
    id: D8
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 5

  - pin: 14
    id: B12
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 6

  - pin: 15
    id: B11
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 7

  - pin: 16
    id: B10
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: AUX 8
    
  # High side
  
  - pin: 17
    id: E15
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 1
    
  - pin: 18
    id: E14
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 2
    
  - pin: 19
    id: E13
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 3
    
  - pin: 20
    id: E12
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 4
    
  - pin: 21
    id: E11
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 5
    
  - pin: 22
    id: E10
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 6
    
  - pin: 23
    id: E9
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 7
    
  - pin: 24
    id: E8
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 8
    
  # SENSORS
  
  - pin: 25
    id: EFI_ADC_0
    class: analog_inputs
    function: Sensor Input
    ts_name: Battery reference voltage

  - pin: 26
    id: EFI_ADC_1
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 1

  - pin: 27
    id: EFI_ADC_2
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 2

  - pin: 28
    id: EFI_ADC_3
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 3

  - pin: 29
    id: EFI_ADC_12
    class: analog_inputs
    function: Sensor Input
    ts_name: MAP sensor

  - pin: 30
    id: EFI_ADC_11
    class: analog_inputs
    function: Sensor Input
    ts_name: Build-in wideband sensor 1

  - pin: 31
    id: EFI_ADC_10
    class: analog_inputs
    function: Sensor Input
    ts_name: Build-in wideband sensor 2

  - pin: 32
    id: EFI_ADC_5
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 4

  - pin: 33
    id: EFI_ADC_4
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 5

  - pin: 34
    id: EFI_ADC_6
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 6

  - pin: 35
    id: EFI_ADC_7
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 7
  
  - pin: 36
    id: EFI_ADC_15
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 8

  - pin: 37
    id: EFI_ADC_14
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 9

  - pin: 38
    id: EFI_ADC_8
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 10

  - pin: 39
    id: EFI_ADC_9
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 11

  - pin: 40
    id: EFI_ADC_13
    class: analog_inputs
    function: Sensor Input
    ts_name: Analog Input 12

  - pin: 41
    id: [E5, E5]
    class: [event_inputs, switch_inputs]
    function: Camshaft Sensor (VR+/Hall)
    type: hall
    ts_name: Camshaft Sensor

  - pin: 42
    id: [E6, E6]
    class: [event_inputs, switch_inputs]
    function: Crankshaft Sensor (VR+/Hall)
    type: hall
    ts_name: Crankshaft Sensor

  - pin: 43
    id: [E4, E4]
    class: [event_inputs, switch_inputs]
    function: Spare trigger input (VR+/Hall)
    type: hall
    ts_name: Spare trigger input 1

  - pin: 44
    id: [C13, C13]
    class: [event_inputs, switch_inputs]
    function: Spare trigger input (VR+/Hall)
    type: hall
    ts_name: Spare trigger input 2

  - pin: 45
    id: [E1, E1]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 1

  - pin: 46
    id: [E0, E0]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 2

  - pin: 47
    id: [E2, E2]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 3

  - pin: 48
    id: [E3, E3]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 4

  - pin: 49
    id: [F0, F0]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 5

  - pin: 50
    id: [F1, F1]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 6

  - pin: 51
    id: [F2, F2]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 7

  - pin: 52
    id: [F6, F6]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 8

info:
  title: APEX
  name: Main Connector
  board_url: 
  directory: APEX
  cid: main
  order: 0
  image:
    file: KRYPTON.png
  pins:
    - pin: 1
      x: 1508
      y: 958
    - pin: 2
      x: 1508
      y: 787
    - pin: 3
      x: 1508
      y: 616
    - pin: 4
      x: 1508
      y: 445
    - pin: 5
      x: 1363
      y: 958
    - pin: 6
      x: 1363
      y: 787
    - pin: 7
      x: 1363
      y: 616
    - pin: 8
      x: 1363
      y: 445
    - pin: 9
      x: 1217
      y: 958
    - pin: 10
      x: 1217
      y: 787
    - pin: 11
      x: 1217
      y: 616
    - pin: 12
      x: 1217
      y: 445
    - pin: 13
      x: 1114
      y: 958
    - pin: 14
      x: 1114
      y: 787
    - pin: 15
      x: 1114
      y: 616
    - pin: 16
      x: 1114
      y: 445
    - pin: 17
      x: 1011
      y: 958
    - pin: 18
      x: 1011
      y: 787
    - pin: 19
      x: 1011
      y: 616
    - pin: 20
      x: 1011
      y: 445
    - pin: 21
      x: 908
      y: 958
    - pin: 22
      x: 908
      y: 787
    - pin: 23
      x: 908
      y: 616
    - pin: 24
      x: 908
      y: 445
    - pin: 25
      x: 805
      y: 958
    - pin: 26
      x: 805
      y: 787
    - pin: 27
      x: 805
      y: 616
    - pin: 28
      x: 805
      y: 445
    - pin: 29
      x: 702
      y: 958
    - pin: 30
      x: 702
      y: 787
    - pin: 31
      x: 702
      y: 616
    - pin: 32
      x: 702
      y: 445
    - pin: 33
      x: 599
      y: 958
    - pin: 34
      x: 599
      y: 787
    - pin: 35
      x: 599
      y: 616
    - pin: 36
      x: 599
      y: 445
    - pin: 37
      x: 496
      y: 958
    - pin: 38
      x: 496
      y: 787
    - pin: 39
      x: 496
      y: 616
    - pin: 40
      x: 496
      y: 445
    - pin: 41
      x: 393
      y: 958
    - pin: 42
      x: 393
      y: 787
    - pin: 43
      x: 393
      y: 616
    - pin: 44
      x: 393
      y: 445
    - pin: 45
      x: 290
      y: 958
    - pin: 46
      x: 290
      y: 787
    - pin: 47
      x: 290
      y: 616
    - pin: 48
      x: 290
      y: 445



    
 

