package peak.can.basic;

/** Stub for PEAK PCAN channel handles. Replace with the real library on Windows. */
public enum TPCANHandle {
    PCAN_NONEBUS,
    PCAN_ISABUS1, PCAN_ISABUS2, PCAN_ISABUS3, PCAN_ISABUS4,
    PCAN_ISABUS5, PCAN_ISABUS6, PCAN_ISABUS7, PCAN_ISABUS8,
    PCAN_DNGBUS1,
    PCAN_PCIBUS1, PCAN_PCIBUS2, PCAN_PCIBUS3, PCAN_PCIBUS4,
    PCAN_PCIBUS5, PCAN_PCIBUS6, PCAN_PCIBUS7, PCAN_PCIBUS8,
    PCAN_USBBUS1, PCAN_USBBUS2, PCAN_USBBUS3, PCAN_USBBUS4,
    PCAN_USBBUS5, PCAN_USBBUS6, PCAN_USBBUS7, PCAN_USBBUS8,
    PCAN_PCCBUS1, PCAN_PCCBUS2,
    PCAN_LANBUS1, PCAN_LANBUS2, PCAN_LANBUS3, PCAN_LANBUS4,
    PCAN_LANBUS5, PCAN_LANBUS6, PCAN_LANBUS7, PCAN_LANBUS8,
}
