// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on /home/dflak/fome-fw/firmware/config/boards/mikrus_df/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A8:
			return "IN8 - Injector 8 (A8)";
		case Gpio::B4:
			return "IN2 - Injector 2 (B4)";
		case Gpio::B5:
			return "IN3 - Injector 3 (B5)";
		case Gpio::B6:
			return "IN4 - Injector 4 (B6)";
		case Gpio::B7:
			return "IN5 - Injector 5 (B7)";
		case Gpio::B8:
			return "IN6 - Injector 6 (B8)";
		case Gpio::B9:
			return "IN7 - Injector 7 (B9)";
		case Gpio::C6:
			return "HALL1 - Primary Trigger (C6)";
		case Gpio::D10:
			return "ETB Direction (D10)";
		case Gpio::D11:
			return "ETB Disable (D11)";
		case Gpio::D12:
			return "ETB PWM (D12)";
		case Gpio::D3:
			return "IGN2 - Ignition 2 (D3)";
		case Gpio::D4:
			return "IGN1 - Ignition 1 (D4)";
		case Gpio::D7:
			return "IN1 - Injector 1 (D7)";
		case Gpio::E11:
			return "HALL2 - Secondary Trigger (E11)";
		case Gpio::E3:
			return "LED Red / Error (E3)";
		case Gpio::E4:
			return "LED Green 1 / Comms (E4)";
		case Gpio::E5:
			return "LED Green 2 / Running (E5)";
		case Gpio::E6:
			return "LED Orange / Warning (E6)";
		case Gpio::E7:
			return "VR1 - VR/Hall Input (E7)";
		default:
			return nullptr;
	}
	return nullptr;
}
