pins:
  - id: EFI_ADC_20
    class: analog_inputs
    ts_name: G0 Analog 1

  - id: EFI_ADC_21
    class: analog_inputs
    ts_name: G0 Analog 2

  - id: EFI_ADC_22
    class: analog_inputs
    ts_name: G0 Analog 3

  - id: EFI_ADC_23
    class: analog_inputs
    ts_name: G0 Analog 4

  - id: EFI_ADC_24
    class: analog_inputs
    ts_name: G0 Analog 5

  - id: EFI_ADC_25
    class: analog_inputs
    ts_name: G0 Analog 6

  - id: EFI_ADC_26
    class: analog_inputs
    ts_name: G0 Analog 7

  - id: EFI_ADC_27
    class: analog_inputs
    ts_name: G0 Analog 8

  - id: EFI_ADC_28
    class: analog_inputs
    ts_name: G0 Analog Temp 1

  - id: EFI_ADC_29
    class: analog_inputs
    ts_name: G0 Analog Temp 2

  - id: EFI_ADC_30
    class: analog_inputs
    ts_name: G0 Analog Temp 3

  - id: EFI_ADC_31
    class: analog_inputs
    ts_name: G0 Analog Temp 4

  - id: G0_DIGITAL_IN_0
    class: switch_inputs
    ts_name: G0 Digital 1

  - id: G0_DIGITAL_IN_1
    class: switch_inputs
    ts_name: G0 Digital 2

  - id: G0_DIGITAL_IN_2
    class: switch_inputs
    ts_name: G0 Digital 3

  - id: G0_DIGITAL_IN_3
    class: switch_inputs
    ts_name: G0 Digital 4

  - id: G0_LOWSIDE_0
    class: outputs
    ts_name: G0 Lowside 1

  - id: G0_LOWSIDE_1
    class: outputs
    ts_name: G0 Lowside 2

  - id: G0_LOWSIDE_2
    class: outputs
    ts_name: G0 Lowside 3

  - id: G0_LOWSIDE_3
    class: outputs
    ts_name: G0 Lowside 4
