

ifeq ($(LED_CRITICAL_ERROR_BRAIN_PIN),)
  LED_CRITICAL_ERROR_BRAIN_PIN = -DLED_CRITICAL_ERROR_BRAIN_PIN=H64_LED1_RED
endif

DDEFS += $(LED_CRITICAL_ERROR_BRAIN_PIN)

DDEFS += -DHELLEN_BOARD_ID_PIN_1=Gpio::C2 -DHELLEN_BOARD_ID_PIN_2=Gpio::C3

include $(BOARDS_DIR)/hellen/hellen-common.mk
